title: EEG Music Challenge
description: EEG Music Challenge at ICASSP 2025
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
challenge:
  name: "AIPAD: AI in Pancreatic Disease Detection and Diagnosis"
  short: AIPAD
  host: "ICASSP 2025<br>Marrakesh, Morocco<br>October 6-10, 2024 (TBD)"
  submission_link: https://cmt3.research.microsoft.com/AIPAD2024
  dates:
    submission: June 24, 2024
    decision: July 15, 2024
    camera_ready: July 30, 2024
    workshop: October 10, 2024
  organizers:
    - name: Federica
      surname: Proietto Salanitri
      affiliation: University of Catania
      email: federica.proiettosalanitri@unict.it
      pic: img/federica.jpg
    - name: Serestina
      surname: Viriri
      affiliation: University of KwaZulu-Natal
      email: 
      pic: img/serestina_viriri.jpg
    - name: Ulas
      surname: Bagci
      affiliation: Northwestern University
      email: 
      pic: img/pic.jpg
    - name: Pallavi
      surname: Tiwari
      affiliation: University of Wisconsin-Madison
      email: 
      pic: img/pic.jpg
    - name: Boqing
      surname: Gong
      affiliation: Google
      email: 
      pic: img/pic.jpg
    - name: Concetto
      surname: Spampinato
      affiliation: University of Catania
      email: concetto.spampinato@unict.it
      pic: img/concetto.jpg
  pc:
    - name: Giovanni
      surname: Bellitto
      affiliation: University of Catania
    - name: Salvatore 
      surname: Calcagno
      affiliation: University of Catania
    - name: Tolga  
      surname: Cukur
      affiliation: Bilkent University
    - name: Rutger   
      surname: Hendrix
      affiliation: Università Campus Bio-Medico Rome
    - name: Davood
      surname: Karimi
      affiliation: Boston Children's Hospital
    - name: Aggelos 
      surname: Katsaggelos
      affiliation: Northwestern University
    - name: Raffaele 
      surname: Mineo
      affiliation: Università Campus Bio-Medico Rome
    - name: Simone 
      surname: Palazzo
      affiliation: University of Catania
    - name: Matteo   
      surname: Pennisi
      affiliation: Università Campus Bio-Medico Rome
    - name: Ziyue  
      surname: Xu
      affiliation: NVIDIA
    - name: Jing 
      surname: Yuan
      affiliation: Zhejiang University
  talks:
    - name: "Zongwei Zhou"
      affiliation: "Johns Hopkins University"
      pic: img/Zhou.jpeg
      title: "Analysis of Pancreatic Tumors by Synthesis"
      file_text: "PDF"
      file_url: 
      bio: "Zongwei Zhou is an assistant research scientist at Johns Hopkins University. He received his Ph.D. in Biomedical Informatics at Arizona State University in 2021. His research focuses on developing novel methods to reduce the annotation efforts for computer-aided detection and diagnosis. Zongwei received the AMIA Doctoral Dissertation Award in 2022, the Elsevier-MedIA Best Paper Award in 2020, and the MICCAI Young Scientist Award in 2019. In addition to seven U.S. patents, Zongwei has published over 30 peer-reviewed journal/conference articles, two of which have been ranked among the most popular articles in IEEE TMI and the highest-cited article in EJNMMI Research. He was named the top 2% of Scientists released by Stanford University in 2022 and 2023."
  program:
    
