title: EEG-Music Emotion Recognition Challenge
description: EEG Music Emotion Recognition Challenge at ICASSP 2025
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
workshop:
  name: "EEG-Music Emotion Recognition"
  short: EREMUS
  host: "ICASSP 2025<br>Hyderabad, India<br>April 6-11, 2025 (TBD)"
  submission_link: 
  dates:
    launch: September 2, 2024
    dataset: September 9, 2024
    submission: November 25, 2024
    leaderboard: November 27, 2024
    paper: December 9, 2024
    decision: December 30, 2024
    camera_ready: January 13, 2025
    session: TBD
  organizers:
    - name: Salvatore
      surname: Calcagno
      affiliation: University of Catania
      email: salvatore.calcagno@phd.unict.it
      pic: img/salvo.JPG
    - name: Simone
      surname: Carnemolla
      affiliation: University of Catania
      email: simone.carnemolla@phd.unict.it
      pic: img/pic.jpg
    - name: Isaak
      surname: Kavasidis
      affiliation: University of Catania
      email: kavasidis@unict.it
      pic: img/pic.jpg
    - name: Simone
      surname: Palazzo
      affiliation: University of Catania
      email: simone.palazzo@unict.it
      pic: img/pic.jpg
    - name: Daniela
      surname: Giordano
      affiliation: University of Catania
      email: daniela.giordano@unict.it
      pic: img/pic.jpg
    - name: Concetto
      surname: Spampinato
      affiliation: University of Catania
      email: concetto.spampinato@unict.it
      pic: img/concetto.jpg
    
